### ISSUE TITLE
YouTube auth tokens can't be retrieved

### ISSUE THREAD

**Issue by lMolMol** [devoxin/lavaplayer#14]
I have been getting this error since yesterday.

15:02:13.728 lava-daemon-pool-info-loader-2-thr            YoutubeAccessTo WARN   YouTube auth tokens can't be retrieved because email and password is unset in YoutubeAudioSourceManager, age restricted videos may throw exceptions.
15:02:14.114 lava-daemon-pool-info-loader-2-thr            YoutubeSignatur DEBUG  Parsing player script /s/player/018e9916/player_ias.vflset/en_GB/base.js
15:02:14.172 JDA Gateway-Worker 1                          WebSocketClient DEBUG  Sending voice request {"op":4,"d":{"self_deaf":false,"guild_id":750554274865479723,"channel_id":1152627695688105984,"self_mute":false}}
15:02:14.509 lava-daemon-pool-info-loader-2-thr            YoutubeAccessTo INFO   Updating YouTube visitor id (current is null).
15:02:14.547 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Using encryption mode xsalsa20_poly1305_lite
15:02:14.578 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Unknown Audio OP code.
{"op":18,"d":{"user_id":"692598549484929052","flags":2}}
15:02:14.578 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Unknown Audio OP code.
{"op":18,"d":{"user_id":"1024478956952502312","flags":0}}
15:02:14.578 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Unknown Audio OP code.
{"op":20,"d":{"user_id":"692598549484929052","platform":0}}
15:02:14.578 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Unknown Audio OP code.
{"op":20,"d":{"user_id":"1024478956952502312","platform":0}}
15:02:14.608 JDA AudioWS-ReadThread (guildId: 7            AudioWebSocket  DEBUG  Audio connection has finished connecting!
15:02:14.646 lava-daemon-pool-info-loader-2-thr            YoutubeAccessTo INFO   Updating YouTube visitor id succeeded, new one is CgtySHBLT2hvMDFNUSjG-7OyBjIKCgJDQRIEGgAgQzoMCAEg-6To2OS4v6Zm, next update will be after 600 seconds.
15:02:14.646 lava-daemon-pool-info-loader-2-thr            DefaultYoutubeT DEBUG  Loading track info with payload: {"context":{"thirdParty":{"embedUrl":"https://google.com"},"client":{"androidSdkVersion":30,"clientName":"ANDROID","clientScreen":"EMBED","clientVersion":"18.11.34","visitorData":"CgtySHBLT2hvMDFNUSjG-7OyBjIKCgJDQRIEGgAgQzoMCAEg-6To2OS4v6Zm"},"user":{"lockedSafetyMode":false}},"racyCheckOk":true,"contentCheckOk":true,"videoId":"VYJGMftYtY4","playbackContext":{"contentPlaybackContext":{"signatureTimestamp":"19863"}},"params":"CgIQBg"}
15:02:14.709 lava-daemon-pool-info-loader-2-thr            DefaultAudioPla DEBUG  No matches for track with identifier https://music.youtube.com/watch?v=VYJGMftYtY4.
no match
15:02:15.075 JDA RateLimit-Elastic-Worker 2                Requester       DEBUG  Received response with following cf-rays: [887729bb8f362cd1-ORD]
15:02:15.076 JDA RateLimit-Elastic-Worker 2                RestRateLimiter DEBUG  Caching bucket hash POST/interactions/{interaction_id}/{interaction_token}/callback -> 432f6223265d156004ac81366c5a948f
15:02:27.086 JDA RateLimit-Scheduler-Worker 2              RestRateLimiter DEBUG  Removed 2 expired buckets

**Comment by pablo67340** [comment]
Testing a fix now, hoping to PR soon

UPDATE:

Looks like their API is now expecting "device_code" instead of just "code" in the Auth Token Request Constant. Still working on it here to see if this would also fix non-logged in users.

**Comment by lMolMol** [comment]
> Testing a fix now, hoping to PR soon
> 
> UPDATE:
> 
> Looks like their API is now expecting "device_code" instead of just "code" in the Auth Token Request Constant. Still working on it here to see if this would also fix non-logged in users.

Thank you for the update and your hard work on this fix!

**Comment by Splayfery** [comment]
Does that mean i can't play yt videos until the code gets updated?

**Comment by devoxin** [comment]
The built-in source manager is deprecated as of `1.9.0` (formal release still pending). It will not be receiving any further updates as its replacement is [`youtube-source`](https://github.com/lavalink-devs/youtube-source). To use with my Lavaplayer fork, you will need the `common` package. Logging into accounts is not supported with that source due to issues with authentication, security concerns and the maintenance needed to support such a feature.
