### ISSUE TITLE
Can't play a song LOAD_FAILED

### ISSUE THREAD

**Issue by NPExce** [devoxin/lavaplayer#17]
Hi,

when I'm trying to play song from yt nothing happened.

On the beginning program is in AudioLoadResultHandler.playlistLoaded and everything looks fine. But immediately when program goes out,  I'm in AudioEventAdapter.onTrackEnd and last parameter AudioTrackEndReason is "LOAD_FAILED". 
Also on first run of song, appears one error "2024-07-28 23:10:15.816 ERROR 21688 --- [back-1-thread-1] .s.d.l.s.y.YoutubeSignatureCipherManager : Problematic YouTube player script /s/player/1f8742dc/player_ias.vflset/xx_XX/base.js detected (issue detected with script: no n function match). Dumped to C:\Users\XXX\AppData\Local\Temp\lavaplayer-yt-player-script9713398708879842367.js"

No other errors in console.

**Comment by devoxin** [comment]
Built-in YouTube source is deprecated.
